export const CHECK_TOKEN_SUCCESS ='CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILED ='CHECK_TOKEN_FAILED';
export const CHECK_TOKEN_PENDING ='CHECK_TOKEN_PENDING';

export const SIGN_IN_SUCCESS ='SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED ='SIGN_IN_FAILED';
export const SIGN_IN_PENDING ='SIGN_IN_PENDING';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';


export const GET_CLIENTS_SUCCESS ='GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILED ='GET_CLIENTS_FAILED';
export const GET_CLIENTS_PENDING ='GET_CLIENTS_PENDING';

export const GET_CLIENT_SUCCESS ='GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAILED ='GET_CLIENT_FAILED';
export const GET_CLIENT_PENDING ='GET_CLIENT_PENDING';

export const ADD_CLIENT_SUCCESS ='ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILED ='ADD_CLIENT_FAILED';
export const ADD_CLIENT_PENDING ='ADD_CLIENT_PENDING';

export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILED = 'DELETE_CLIENT_FAILED';
export const DELETE_CLIENT_PENDING = 'DELETE_CLIENT_PENDING';

export const UPDATE_CLIENT_SUCCESS ='UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILED ='UPDATE_CLIENT_FAILED';
export const UPDATE_CLIENT_PENDING ='UPDATE_CLIENT_PENDING';

export const ADD_BANK_DATA_SUCCESS ='ADD_BANK_DATA_SUCCESS';
export const ADD_BANK_DATA_FAILED ='ADD_BANK_DATA_FAILED';
export const ADD_BANK_DATA_PENDING ='ADD_BANK_DATA_PENDING';

export const DELETE_BANK_DATA_SUCCESS ='DELETE_BANK_DATA_SUCCESS';
export const DELETE_BANK_DATA_FAILED ='DELETE_BANK_DATA_FAILED';
export const DELETE_BANK_DATA_PENDING ='DELETE_BANK_DATA_PENDING';

export const UPDATE_BANK_DATA_SUCCESS ='UPDATE_BANK_DATA_SUCCESS';
export const UPDATE_BANK_DATA_FAILED ='UPDATE_BANK_DATA_FAILED';
export const UPDATE_BANK_DATA_PENDING ='UPDATE_BANK_DATA_PENDING';

